sudo: required
dist: trusty
language: cpp
compiler: gcc
addons:
    apt:
        packages:
            - cmake
            - libzmq3
            - libzmq3-dev
            - libzmqpp3
            - libzmqpp-dev
            - libjson-c-dev
            - libxen-dev
install:
    - cd drakvuf/libvmi && ./autogen.sh && ./configure --enable-xen --without-xenstore
    - make && sudo make install
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
os:
    - linux
