sudo: false
language: cpp
compiler: gcc
addons:
    apt:
        packages:
            - cmake
            - libzmq3
            - libzmq3-dev
            - libzmqpp3
            - libzmqpp-dev
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
os:
    - linux
